# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='voter_type',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
