# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 06:06
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import election.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_temporary_closed', models.BooleanField(default=False, help_text='Election temporary closed')),
                ('is_finished', models.BooleanField(db_index=True, default=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_key_required', models.BooleanField(default=True)),
                ('keep_nota_option', models.BooleanField(default=True, help_text='Keep None of The Above as a valid vote in posts')),
                ('session_timeout', models.PositiveSmallIntegerField(default=120, help_text='Seconds after which session will be timed out', validators=[django.core.validators.MaxValueValidator(600)])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalElection',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_temporary_closed', models.BooleanField(default=False, help_text='Election temporary closed')),
                ('is_finished', models.BooleanField(db_index=True, default=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_key_required', models.BooleanField(default=True)),
                ('keep_nota_option', models.BooleanField(default=True, help_text='Keep None of The Above as a valid vote in posts')),
                ('session_timeout', models.PositiveSmallIntegerField(default=120, help_text='Seconds after which session will be timed out', validators=[django.core.validators.MaxValueValidator(600)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical election',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField(max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(default=election.models.generate_random_voter_key, max_length=6)),
                ('voted', models.BooleanField(db_index=True, default=False)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='election.Election')),
                ('tags', models.ManyToManyField(blank=True, to='election.Tag')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together=set([('roll_no', 'election')]),
        ),
    ]
