# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
