# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20160303_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='voters_per_ip',
            field=models.PositiveSmallIntegerField(default=0, help_text='Max votes allowed per IP. Keep it 0 to allow unlimited votes per IP'),
        ),
        migrations.AddField(
            model_name='historicalelection',
            name='voters_per_ip',
            field=models.PositiveSmallIntegerField(default=0, help_text='Max votes allowed per IP. Keep it 0 to allow unlimited votes per IP'),
        ),
    ]
