# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_election_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='voted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together=set([('roll_no', 'election')]),
        ),
    ]
