# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_auto_20160311_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='voters_per_ip',
            new_name='votes_per_ip',
        ),
        migrations.RenameField(
            model_name='historicalelection',
            old_name='voters_per_ip',
            new_name='votes_per_ip',
        ),
    ]
