# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-14 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_auto_20160312_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='is_finished',
            field=models.BooleanField(db_index=True, default=False, help_text='If checked, election will close!'),
        ),
        migrations.AlterField(
            model_name='election',
            name='is_key_required',
            field=models.BooleanField(default=True, help_text='Keep voting key for election'),
        ),
        migrations.AlterField(
            model_name='election',
            name='is_temporary_closed',
            field=models.BooleanField(default=False, help_text='Election temporarily closed'),
        ),
        migrations.AlterField(
            model_name='historicalelection',
            name='is_finished',
            field=models.BooleanField(db_index=True, default=False, help_text='If checked, election will close!'),
        ),
        migrations.AlterField(
            model_name='historicalelection',
            name='is_key_required',
            field=models.BooleanField(default=True, help_text='Keep voting key for election'),
        ),
        migrations.AlterField(
            model_name='historicalelection',
            name='is_temporary_closed',
            field=models.BooleanField(default=False, help_text='Election temporarily closed'),
        ),
    ]
