# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_auto_20160315_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Check it to start Election'),
        ),
        migrations.AlterField(
            model_name='historicalelection',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Check it to start Election'),
        ),
    ]
