# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 23:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_auto_20160204_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='added_by',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 4, 23, 33, 17, 723187, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 4, 23, 33, 24, 660267, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
