# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0012_auto_20160205_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.SlugField(max_length=16, unique=True),
        ),
    ]
