# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0013_auto_20160205_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='type',
        ),
    ]
