# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0014_remove_voter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='session_timeout',
            field=models.PositiveSmallIntegerField(default=120, help_text='Seconds after which session will be timed out'),
        ),
        migrations.AddField(
            model_name='historicalelection',
            name='session_timeout',
            field=models.PositiveSmallIntegerField(default=120, help_text='Seconds after which session will be timed out'),
        ),
    ]
