# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 00:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import election.models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0015_auto_20160209_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='session_timeout',
            field=models.PositiveSmallIntegerField(default=120, help_text='Seconds after which session will be timed out', validators=[django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AlterField(
            model_name='historicalelection',
            name='session_timeout',
            field=models.PositiveSmallIntegerField(default=120, help_text='Seconds after which session will be timed out', validators=[django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AlterField(
            model_name='voter',
            name='key',
            field=models.CharField(default=election.models.generate_random_voter_key, max_length=6),
        ),
    ]
