# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import post.models.candidate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to=post.models.candidate.candidate_image_upload)),
                ('order', models.IntegerField(default=0, help_text='Sorting order of candidates')),
                ('is_nota', models.BooleanField(default=False, editable=False)),
                ('is_neutral', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('number', models.IntegerField(default=1)),
                ('type', models.IntegerField(choices=[(0, 'ALL'), (1, 'UG'), (2, 'PG')], default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='election.Election')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='post.Post'),
        ),
    ]
