# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('number', models.IntegerField(default=1)),
                ('type', models.IntegerField(choices=[[0, 'ALL'], [1, 'UG'], [2, 'PG']], default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='election.Election')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
