# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_candidate_auto_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
