# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import post.models.candidate


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20160214_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=post.models.candidate.candidate_image_upload),
        ),
    ]
