# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20160131_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
