# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.IntegerField(choices=[(0, 'ALL'), (1, 'UG'), (2, 'PG')], default=0),
        ),
    ]
