# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import post.models.candidate


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20160214_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='manifesto',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=post.models.candidate.candidate_image_upload),
        ),
    ]
