# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import post.models.candidate


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20160206_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.candidate.candidate_image_upload),
        ),
    ]
