# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 03:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='casted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 30, 3, 48, 48, 752526, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
