# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_vote_casted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='neutral',
            field=models.BooleanField(default=False),
        ),
    ]
