# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20160204_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='neutral',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='no',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='yes',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.SmallIntegerField(choices=[(0, 'Neutral'), (1, 'Yes'), (-1, 'No')], default=0),
        ),
    ]
