# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_historicalvoteipmap_voteipmap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvoteipmap',
            old_name='timestamp',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='voteipmap',
            old_name='timestamp',
            new_name='ip',
        ),
    ]
